linters-settings:
  misspell:
    locale: US
linters:
  disable-all: true
  enable:
    - nakedret
    - interfacer
    - varcheck
    - deadcode
    - structcheck
    - misspell
    - maligned
    - ineffassign
    - goconst
    - goimports
    - dupl
    - unparam
    - golint
    - staticcheck
    - unused
    - gosimple
    - unconvert
    - gocyclo
