---
 
global:
  writeToFile: true
  metricsDirectory: collected-metrics
  measurements:
    - name: podLatency
      esIndex: kube-burner-podlatency

  indexerConfig:
    enabled: true
    esServers: [https://es-instance.example.org:9200]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic

jobs:
  - name: kube-burner-job
    jobType: create
    jobIterations: 5
    qps: 20
    burst: 40
    namespacedIterations: true
    cleanup: true
    namespace: kube-burner-job-ns
    podWait: false
    waitWhenFinished: true
    waitFor: ["Deployment"]
    verifyObjects: true
    errorOnVerify: false
    jobIterationDelay: 0
    jobPause: 1000
    objects:

      - objectTemplate: objectTemplates/svc.yml
        replicas: 1

      - objectTemplate: objectTemplates/deployment.yml
        replicas: 20
        inputVars:
          containerPort: 8081

      - objectTemplate: objectTemplates/route.yml
        replicas: 2
  
  - name: second-job
    jobType: delete
    waitForDeletion: true
    qps: 10
    burst: 20
    objects:

    - kind: Deployment
      labelSelector: {job: kube-burner-job}
      apiVersion: apps/v1

    - kind: Secret
      labelSelector: {job: kube-burner-job}

    - kind: Secret
      labelSelector: {job: kube-burner-job}
      apiVersion: route.openshift.io/v1
