name: Go

on:
  push:
    branches: [ master ]
    paths-ignore:
    - "**.md"
    - "examples/**"
    - "hack/**"
  pull_request:
    branches: [ master ]
    paths-ignore:
    - "**.md"
    - "examples/**"
    - "hack/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang-version: [1.14, 1.15]
        image-versions:
        - kindest/node:v1.19.0
        - kindest/node:v1.18.0
        - kindest/node:v1.17.0
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.golang-version}}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: make build

    - name: Install
      run: sudo make install

    - name: Setup kinD
      uses: engineerd/setup-kind@v0.4.0
      with:
        config: test/kind.yml 
        image: ${{matrix.image-versions}}
        version: "v0.7.0"
  
    - name: Execute kube-burner test
      working-directory: test
      run: ./run.sh

  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run golangci-lint
      # You may pin to the exact commit or the version.
      # uses: golangci/golangci-lint-action@04eca2038305127fb1e6683425b6864cd5612f2d
      uses: golangci/golangci-lint-action@v1.2.1
      with:
        # version of golangci-lint to use in form of v1.2.3
        version: v1.30
        # if set to true and the action runs on a pull request - the action outputs only newly found issues
        only-new-issues: true
        # golangci-lint command line arguments
        #args: # optional, default is 
        # golangci-lint working directory, default is project root
        #working-directory: # optional
        # the token is used for fetching patch of a pull request to show only new issues
        #github-token: # default is ${{ github.token }}

  build-container:
    name: Build container image
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - run: make images

